### ISSUE TITLE
How to install minpy and opencv correctly ?

### ISSUE THREAD

**Issue by GerrieWell** [GarrickLin/py-siamese_fc#1]
I followed this [page](https://minpy.readthedocs.io/en/latest/get-started/install.html) to install minpy .
After that ,it seem like install in virtual environment.
if I run `workon minpy_dev` 
python -c 'import minpy.numpy as np' work fine.
But 
```
 python -c 'import cv2' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named cv2
```

If I don't run `workon minpy_dev` .`opencv` work fine .but `minpy` module can't be found .How to fix that ?

**Comment by GarrickLin** [comment]
you dont need to create another virtualenv, and make sure you have installed `cv2.pyd` in `site-packages`

**Comment by GerrieWell** [comment]
Hey.Thank for your suggestion .I solve the library problem.But the program crashs during run-time , at line 315.Can u take a look at it ?What does it mean?
Is it something wrong while loading model ? I didn't modify or add anything .

```
python run_tracker.py
[16:04:32] /Users/gerrie/SDKs/mxnet/dmlc-core/include/dmlc/./logging.h:300: [16:04:32] src/c_api/c_api_ndarray.cc:271: Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered

Stack trace returned 4 entries:
[bt] (0) 0   libmxnet.so                         0x0000000103287c48 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x0000000103840f3d MXImperativeInvoke + 13453
[bt] (2) 2   _ctypes.so                          0x00000001027797ef ffi_call_unix64 + 79
[bt] (3) 3   ???                                 0x00007fff5d8ae890 0x0 + 140734762772624

Traceback (most recent call last):
  File "run_tracker.py", line 386, in <module>
    tracker()
  File "run_tracker.py", line 315, in tracker
    net_z.bind(data_shapes=data_iter.provide_data, for_training=False)
  File "/Users/gerrie/SDKs/mxnet/python/mxnet/module/module.py", line 344, in bind
    grad_req=grad_req, input_types=input_types)
  File "/Users/gerrie/SDKs/mxnet/python/mxnet/module/executor_group.py", line 193, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/Users/gerrie/SDKs/mxnet/python/mxnet/module/executor_group.py", line 232, in bind_exec
    self.execs.append(self._bind_ith_exec(i, data_shapes, label_shapes, shared_group))
  File "/Users/gerrie/SDKs/mxnet/python/mxnet/module/executor_group.py", line 511, in _bind_ith_exec
    context, self.logger)
  File "/Users/gerrie/SDKs/mxnet/python/mxnet/module/executor_group.py", line 489, in _get_or_reshape
    arg_arr = nd.zeros(arg_shape, context, dtype=arg_type)
  File "/Users/gerrie/SDKs/mxnet/python/mxnet/ndarray.py", line 1055, in zeros
    return _internal._zeros(shape=shape, ctx=ctx, dtype=dtype)
  File "/Users/gerrie/SDKs/mxnet/python/mxnet/_ctypes/ndarray.py", line 131, in generic_ndarray_function
    c_array(ctypes.c_char_p, [c_str(str(i)) for i in kwargs.values()])))
  File "/Users/gerrie/SDKs/mxnet/python/mxnet/base.py", line 75, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:04:32] src/c_api/c_api_ndarray.cc:271: Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered

Stack trace returned 4 entries:
[bt] (0) 0   libmxnet.so                         0x0000000103287c48 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x0000000103840f3d MXImperativeInvoke + 13453
[bt] (2) 2   _ctypes.so                          0x00000001027797ef ffi_call_unix64 + 79
[bt] (3) 3   ???                                 0x00007fff5d8ae890 0x0 + 140734762772624
```

**Comment by GerrieWell** [comment]
Solved
